---
- name: Provision and configure Docker host
  hosts: docker_hosts
  become: yes

  tasks:
    # Update the package cache and upgrade the system packages
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: dist

    # Install dependencies required for Docker
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
          - curl
          - lsb-release
        state: present

    # Add Docker's official GPG key
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Add Docker's official APT repository
    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    # Install Docker
    - name: Install Docker
      apt:
        name:
	  - docker-ce
	  - docker-ce-cli
	  - containerd.io
	  - docker-buildx-plugin
	  - docker-compose-plugin
        state: present

    # Add the current user to the docker group
    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Enable Docker service
    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started